language: python
env: PYTHON_VERSION=3.7.0
python:
  - "3.7.0"

install:
  - pip install pyflow
  - pip install flask
  - pip install coverage
  - pip install pytest-cov
  - pip install codecov

script:
  - pytest
  - pytest --cov-report term --cov=./flaskr/app/tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov -t 5ee6744e-1f75-425d-b147-a3bbe7eabf98