language: python
env: PYTHON_VERSION=3.7.0
python:
  - "3.7.0"

install:
  - pip install pyflow
  - pip install flask
  - pip install coverage
  - pip install pytest-cov

script:
  - pytest
  - pytest --cov=./flaskr/app/tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)
